/**
 * Curated dictionary of common technical skills. Used as a deterministic
 * fallback for resume skill extraction when the Claude CLI is unavailable,
 * and to normalise skill tokens during matching.
 */
export const KNOWN_SKILLS: string[] = [
  'JavaScript',
  'TypeScript',
  'React',
  'Next.js',
  'Redux',
  'Node.js',
  'Express',
  'NestJS',
  'HTML',
  'CSS',
  'Tailwind',
  'SASS',
  'Angular',
  'Vue',
  'Java',
  'Spring Boot',
  'Kotlin',
  'Python',
  'Django',
  'Flask',
  'FastAPI',
  'C',
  'C++',
  'C#',
  '.NET',
  'Go',
  'Rust',
  'PHP',
  'Laravel',
  'Ruby',
  'Rails',
  'SQL',
  'MySQL',
  'PostgreSQL',
  'MongoDB',
  'Redis',
  'GraphQL',
  'REST',
  'Docker',
  'Kubernetes',
  'AWS',
  'Azure',
  'GCP',
  'Terraform',
  'CI/CD',
  'Git',
  'Jenkins',
  'Kafka',
  'RabbitMQ',
  'Elasticsearch',
  'Machine Learning',
  'TensorFlow',
  'PyTorch',
  'Pandas',
  'NumPy',
  'Data Analysis',
  'Selenium',
  'Cypress',
  'Jest',
  'Playwright',
  'React Native',
  'Flutter',
  'Swift',
  'Objective-C',
]

/** Lower-cased lookup for fast membership checks. */
export const KNOWN_SKILLS_LOWER = new Set(
  KNOWN_SKILLS.map((skill) => skill.toLowerCase()),
)
